name: Deploy to GitHub Pages

# IMPORTANT: This workflow reads from the 'status-data' orphaned branch
#
# Prerequisites:
#   Run once to create the orphaned branch:
#   npm run setup-status-branch
#
# The build process copies status data from the orphaned branch into the site build.

on:
  push:
    branches:
      - main
    paths-ignore:
      # Don't trigger deploy when only monitoring workflows change
      - '.github/workflows/monitor-systems.yml'
      - '.github/workflows/status-update.yml'
  workflow_dispatch:
  # Deploy immediately when critical status updates occur
  # Triggered by status-update.yml when critical issues are detected
  repository_dispatch:
    types: [status-updated]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      # Checkout main branch for site code
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      # Checkout status-data branch for monitoring data
      - name: Checkout status-data branch
        uses: actions/checkout@v4
        with:
          ref: status-data
          path: status-data
          fetch-depth: 1  # Shallow clone for speed

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: main/package-lock.json

      - name: Install dependencies
        working-directory: main
        run: npm ci

      - name: Copy status data to site directory
        working-directory: main
        run: |
          # Copy status data from orphaned branch to site directory
          # This makes it available to the plugin during build
          cp -r ../status-data ./status-data
          echo "✓ Copied status data from orphaned branch"

      - name: Build website
        working-directory: main
        env:
          # Plugin will read committed status data from status-data/
          # GITHUB_TOKEN is provided as fallback if committed data is stale
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: main/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
