name: Status Update

on:
  schedule:
    # Runs every hour to keep status page fresh
    - cron: '0 * * * *'
  workflow_dispatch:
  issues:
    types: [opened, closed, labeled, unlabeled, edited]
  push:
    branches:
      - main
    paths:
      # Only run when non-status files change (prevents infinite loop)
      - '!build/status-data/**'

permissions:
  contents: write  # Required to commit status data changes
  issues: read     # Required to fetch status issues

jobs:
  update-status:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Update status data
        env:
          # Must explicitly pass token to make it available in process.env
          # secrets.GITHUB_TOKEN exists but is NOT in process.env unless you pass it via env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx stentorosaur-update-status
        
      # Status data is now updated in build/status-data/ directory
      # NOTE: We don't commit here to avoid polluting git history with incompatible commit messages
      # 
      # The calculate-metrics.yml workflow reads git history to extract response times from commits
      # made by monitor-systems.yml (format: "🟩 website is up (200 in 145 ms)")
      # 
      # If we commit here with format "🟥 Systems down: website", it breaks metrics extraction.
      # 
      # Instead, status.json and summary.json are updated locally and will be deployed:
      # - On next scheduled deployment (deploy-scheduled.yml runs daily)
      # - On next code push (triggers deploy.yml)
      # - On manual deployment trigger
      #
      # This ensures:
      # 1. Issue changes are reflected in status data
      # 2. Git history remains clean for metrics calculation
      # 3. All three workflows (monitor-systems, calculate-metrics, status-update) work together

